# Generated by Django 4.2.11 on 2026-04-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_barber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='popularity_badge',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
